### ISSUE TITLE
Original Faust DSP code ?

### ISSUE THREAD

**Issue by sletz** [brummer10/slowmo.lv2#1]
Great project ! 

I understand that the DSP code have been generated from Faust DSP (bandsplit.dsp,  delay.dsp and Gain.dsp). Are the original files DSP files somewhere ?

**Comment by brummer10** [comment]
Hi [Stéphane Letz](https://github.com/sletz)
Yes, I've forgotten to add them, done now. Unfortunately I ain't found my base file for the slowgear any more.

**Comment by sletz** [comment]
Thank !
